name: Continuous integration
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    strategy:
      matrix:
        ghc: ['ghc92', 'ghc94', 'ghc96']
        target: ['halide-haskell-playground']
        os: ['ubuntu-latest', 'macos-latest']
    runs-on: ${{ matrix.os }}
    name: Build ${{ matrix.ghc }}.${{ matrix.target }} on ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
    - name: Build
      run: |
        nix build \
          --accept-flake-config \
          --print-build-logs \
          .#${{ matrix.ghc }}.${{ matrix.target }}
